# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'basic_dev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for basic_dev
platform :ios, '17.5'
pod 'Alamofire'
end
